services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb_dev
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
