algoritmo "Enquanto - Letra for diferente de A"
//  
//  
// Função :
// Autor : Fernando Melo
// Data : 16/01/2022
// Seção de Declarações 
var

   letra : caracter

inicio

      //Enquanto <expressão booleana> Faca

      //         <instruções a serem executadas enquanto a expressão booleana resultar em VERDADEIRO>

      //FimEnquanto
      
      Enquanto letra <> "a" faca
      
               Escreval("Digite uma letra: ")
               leia(letra)
      
      FimEnquanto
      
      Escreval("Você digitou a letra A até a próxima!")

fimalgoritmo
