algoritmo "Enquanto número menor que 10 Faca"
//  
//  
// Função :
// Autor : Fernando Melo
// Data : 16/01/2022
// Seção de Declarações 
var

   numero : inteiro

inicio

        numero <- 1
        
        //Vai imprimir o número 9 vezes
        Enquanto numero < 10 Faca
        
                 Escreval(numero)
                 numero <- numero + 1
        
        FimEnquanto

fimalgoritmo
