algoritmo "Exercício Escolha Andar Predio"
//  
//  
// Função :
// Autor : Fernando Melo
// Data : 16/01/2022
// Seção de Declarações 
var

   andarPredio : inteiro

inicio


      Escreval("Digite o número do Andar que deseja comprar: ")
      leia(andarPredio)
      
      Escolha andarPredio
      
              Caso 1
              
                   Escreval("Andar 1 valor de R$ 200.000")
                   
              Caso 2, 3, 4

                   Escreval("Andares 2, 3 e 4 valor de R$ 220.000")
                   
              Caso 5, 6, 7
              
                   Escreval("Andares 5, 6 e 7 valor de R$ 250.000")
                   
              Caso 8, 9, 10
              
                   Escreval("Andares 8, 9 e 10 valor de R$ 300.000")
                   
              Caso 11, 12, 13, 14, 15, 16, 17, 18
              
                   Escreval("Andares entre 11 e 18 valor de R$ 500.000")
                   
              OutroCaso
              
                   Escreval("Não existe um andar com esse número no prédio.")
      
      
      FimEscolha

fimalgoritmo
