algoritmo "Exercício Para-de-ate-Faca Imprimir Sequencia Números"
//  
//  
// Função :
// Autor : Fernando Melo
// Data : 16/04/2026
// Seção de Declarações 
var

   quantidade, numero : inteiro

inicio

      Escreval("Digite um número maior que ZERO")
      leia(numero)
      
      Para quantidade de 0 ate numero Faca
      
           Escreval(quantidade)
      
      FimPara

fimalgoritmo
