Algoritmo "Função Se"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Fernando Melo
// Data atual  : 15/4/2026
Var
// Seção de Declarações das variáveis 
   numero : inteiro

Inicio

      //Se <expressão booleana> Enao
      //   <instruç[oes e serem execultadas caso a expreção booleana resulte em VERDADEIRO>

      //Senao
      
      //     <instruç[oes e serem execultadas caso a expreção booleana resulte em FALSO>
      //FimSe
      
      Escreval("Digite um Número: ")
      leia(numero)
      
      Se (numero > 10 ) Entao
      
         Escreval(numero, " é MAIOR que 10")
         
      Senao
      
           Escreval(numero, " é MENOR que 10")

      Fimse
FimAlgoritmo