algoritmo "Função Se com Ou"
//  
//  
// Função :
// Autor : Fernando Melo
// Data : 12/01/2022
// Seção de Declarações 
var

   cor : caractere

inicio

      Escreval("Digite uma cor: ")
      leia(cor)
      
      Se ( cor = "Azul" ) ou ( cor = "Amarelo" ) Entao
      
           Escreval("A cor digitada é Azul ou Amarelo")
      
      Senao
      
           Escreval("Cor Inválida")
      
      FimSe

fimalgoritmo
