Algoritmo "Olá, Mundo!"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/4/2026
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   // Escreval com a letra 'L' no final faz a quebra do texto para proxima linha
   Escreval("Olá, Mundo!")
   Escreval("Sou o Aluno: Fernando")
   Escreval
   Escreval()
   Escreva("Olá, Mundo! 2 ")
   Escreva("Sou o Aluno: Fernando 2")

Fimalgoritmo