Algoritmo "Tipo de Dados"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/4/2026
Var

   quantidade : inteiro
   preco : real
   totalAPagar : real
   produto : caractere
   cliente : caractere
   compraEfetivada : logico

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   quantidade <- 2
   preco <- 89.80
   totalAPagar <- quantidade * preco
   cliente <- "Ana Paula"
   produto <- "Bolsas"
   compraEfetivada <- VERDADEIRO
   
   Escreval(quantidade)
   Escreval(preco)
   Escreval(totalAPagar)
   Escreval(cliente)
   Escreval(produto)
   Escreval(compraEfetivada)
   Escreval()
   Escreval()
   Escreval("A Cliente ", cliente, " comprou ",quantidade, " ", produto, " e vai pagar o total de ", totalAPagar)

Fimalgoritmo