Algoritmo "Total a pagar Lan Houser"
// 
//  
// Descrição   : Total a pagar Lan Houser
// Autor(a)    : Fernando Melo
// Data atual  : 15/4/2026
Var

   minutos, totalAPagar : real


Inicio

   Escreval("Digite a quantidade em minutos utilizados pelo clienye: ")
   leia(minutos)
   
   totalAPagar <- minutos * ((1/60)*2)
   
   Escreval("Total a Pagar: ", totalAPagar, " reais")


Fimalgoritmo