Algoritmo "Vetor Exemplo 1"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Fernando Melo
// Data atual  : 16/4/2026
Var
// Seção de Declarações das variáveis 
   letraDigitada : vetor [1..4] de caractere
   indice : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Para indice de 1 ate 4 Faca
   
   Escreval("Digite uma Letra")
   leia( letraDigitada[ indice ] )
   
   FimPara
   
   Escreval
   Escreval("Letra Posição 1: ", letraDigitada[1])
   Escreval("Letra Posição 2: ", letraDigitada[2])
   Escreval("Letra Posição 3: ", letraDigitada[3])
   Escreval("Letra Posição 4: ", letraDigitada[4])

Fimalgoritmo